version: 0.1

phases:
    install:
      runtime-versions:
        nodejs: 10
    build:
    commands:
      # Build our react application
      # - npm run build
      echo build will run here
  artifacts:
    files:
    - public/*
    - src/*

